export default {
  home: 'Home',
  detail: 'DetailScreen',
  movie: 'Movie',
  trailer: 'Trailer',
  trending: 'Trending',
  community: 'Community',
  tvShows: 'TV Shows',
  gotoDetail: 'Go to Detail',
  user: 'User',
  streaming: 'Streaming',
  onTv: 'On TV',
  forRent: 'For Rent',
  inTheaters: 'In Theaters',
  today: 'Today',
  thisWeek: ' This Week',
  movies: 'Movies',
  tv: 'TV',
  whatsPoplular: `What's popular`,
  latestTrailer: 'Latest Trailer',
  freeToWatch: 'Free To Watch',
};
